SELECT
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    ORDINAL_POSITION
FROM IDP.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'MAIN'
  AND TABLE_NAME IN (
      'AS_REF_INTR_DIGITAL_MOBILE_APP_VISIT_CNT_24M'
  )
ORDER BY TABLE_NAME, ORDINAL_POSITION;
